#!/usr/bin/env python2

import sys, os
import dogtail, dogtail.utils, dogtail.config

def main(path):
    dogtail.utils.enableA11y()
    filename = os.path.basename(path)
    dirname = os.path.dirname(path)
    if len(dirname) == 0:
        dirname = os.getcwd()
    dogtail.config.config.scratchDir = dirname
    dogtail.utils.screenshot(filename, timeStamp=False)

if __name__ == "__main__":
    if "DISPLAY" not in os.environ:
        os.environ["DISPLAY"] = ":1"
    sys.exit(main(*sys.argv[1:]))
