#!/bin/bash

# Thanks!
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
exec ${DIR}/python_launcher.sh ${DIR}/make_screenshot.py "$@"
