#!/usr/bin/sh

# Multilib safe wrapper for pkg-config to call correct platform-specific version of pkg-config

## Vendored definition of %_target_platform from redhat-rpm-config to avoid depending on it
TARGET_PLATFORM="x86_64-redhat-linux-gnu"

exec "/usr/bin/${TARGET_PLATFORM}-pkg-config" "$@"
